# Theme Settings
minimal_mistakes_skin    : "default"

# Site Settings
locale                   : "zh-CN"
title                    : "我的学习笔记"
title_separator          : "-"
name                     : "zzm"
description              : "个人技术笔记"
url                      : "https://zzzmmmqqq.github.io"
baseurl                  : "/zzm-notes"

# 关闭多余评论、社交，先不用
comments:
  provider               : false

# 搜索关掉先
search                   : false

# 作者信息
author:
  name             : "zzm"
  bio              : "持续学习，记录点滴"

# 阅读、转换配置不变
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
paginate: 5

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# 默认文章布局
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
